version: "3.8"
services:
  redis:
    image: redis
    container_name: redis-cont
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
volumes:
  redis_volume_data:
  redis_insight_volume_data:
